#!/bin/bash

echo "PING emotional-stability.local (127.0.0.1): 56 data bytes"
echo "Request timeout: The host is currently emotionally unavailable."
echo "Request timeout: The host needs some space."
echo "Request timeout: It's not the host, it's you."
