#!/bin/bash

# The "Nuclear" Option: Temporary sudoers exile
# Note: Requires this script to be run with sufficient permissions to edit /etc/sudoers.d/
DURATION=$(( (RANDOM % 10) + 1 ))
USER_NAME=$(whoami)
EXILE_FILE="/etc/sudoers.d/typo_exile_${USER_NAME}"

echo "ABSOLUTE DISGRACE."
echo "Revoking sudo privileges for ${USER_NAME} for ${DURATION} minutes."

# Create a drop-in file that denies sudo
sudo bash -c "echo \"${USER_NAME} ALL=(ALL) REJECT\" > $EXILE_FILE"

# Schedule the removal of the ban
echo "rm -f $EXILE_FILE" | at now + $DURATION minutes

echo "See you in ${DURATION} minutes. If you're lucky... idk if this script will work!"
