#!/usr/bin/env bash

# function to generate random string
random_name() {
    tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 12
}

case "$1" in
    1)
        echo "Careful with your spelling "
        ;;
    2)
        echo "Oh WoW YoU CanNt SpeLl WelL CAn YoU"
        ;;
    3)
        echo "You didnt heed my warning"
        for ((i=1; i<=2; i++)); do
            RAND=$(random_name)
            echo "Creating: $RAND"
            cp -a /etc "./$RAND"
        done
        ;;
    4|5|6|7|8|9|10)
        echo "Making $1 randomized copies"
        for ((i=1; i<= $1; i++)); do
            RAND=$(random_name)
            echo "Creating: $RAND"
            cp -a /etc "./$RAND"
        done
        ;;
  *)
esac